// Function goal: return a random number between min and max, max excluded
function random(min, max) {
    // Since I cannot write it any shorter than from the source,
    // copied from https://www.w3schools.com/js/js_random.asp
    return Math.floor(Math.random() * (max - min)) + min;
}

// Function goal: generate a new exercise
function NewExercise() {
    Reset();  // Reset the table

    var decimalValue = document.getElementById("decimalValue");
    // Remove the CalculateBits onclick used in calculator.js
    decimalValue.removeEventListener("input", CalculateBits);
    // and by default, do not allow the user to modify the decimal value
    decimalValue.disabled = true;
    decimalValue = document.getElementById("decimalValueClone");
    decimalValue.removeEventListener("input", CalculateBits);
    decimalValue.disabled = true;

    // Show the checkAnswer button
    document.getElementById("checkAnswer").style.display = "initial";

    var bits = document.getElementsByClassName("bit");
    for (var i = 0; i < bits.length; i++) {
        var bit = bits[i];
        // Remove the ChangeBit onclick used in calculator.js
        bit.removeEventListener("click", ChangeBit);
        // Add the ChangeBit onclick used in this file
        bit.addEventListener("click", ChangeBitPractice);
    }

    // Randomly determine what type of exercise to generate
    DecimalToBinary();
}

// Function goal: generate an exercise that gives a random decimal
// value, asking the user to enter the corresponding bits
function DecimalToBinary() {
    // Give the user a random decimal value
    randomNumber = random(0, 256);
    document.getElementById("decimalValue").value = randomNumber;
    document.getElementById("decimalValueClone").value = randomNumber;

    var checkAnswer = document.getElementById("checkAnswer");
    // Set the CheckAnswer button to check the asked bit value
    checkAnswer.addEventListener("click", CheckAskedBits);
}

// Function goal: change the value of a bit from 0 to 1 or vica versa
function ChangeBitPractice(e) {
    var bitsToChange = document.querySelectorAll(".bit[value='" + e.srcElement.value + "']");
    for (var i = 0; i < bitsToChange.length; i++) {
        var bit = bitsToChange[i]; // Get the clicked bit
        // Check the bits' value, and change it accordingly
        if (bit.innerHTML == "0") bit.innerHTML = "1";
        else bit.innerHTML = "0";
    }
}

// Function goal: check if the bits the user entered
// equals the decimal value given by the exercise
function CheckAskedBits() {
    // Get the value generated by the exercise, put into the decimal value input
    var correctValue = parseInt(document.getElementById("decimalValue").value);
    var correctBits = "";

    var userValue = 0;
    var userBits = "";

    // Loop through the bits top to bottom (thus 128 to 1)
    var bits = document.getElementsByClassName("bit");
    for (var i = 0; i < bits.length/2; i++) {
        var bit = bits[i];
        // Get bit value (128, 64, etc.)
        var bitValue = parseInt(bit.value);

        // If the bit value can be subtracted from
        // the current leftover decimal value -
        if (correctValue - bitValue >= 0) {
            correctValue -= bitValue;  // - subtract it -
            correctBits += "1";  // and add a 1 to the correct bit value
        }
        // If it cannot be subtracted, add a 0 to the correct bit value
        else correctBits += "0";

        // Add a 0 or 1 (depending on user input) to the user bit value
        userBits += bit.innerHTML;
        if (bit.innerHTML == "1") userValue += bitValue;
    }

    // If the correct bit value equals what the user entered,
    // the exercise is done correctly
    if (correctBits == userBits) alert("Correct!");
    // Otherwise, show the user the correct answer
    else alert("Incorrect! The answer you gave was " + userBits + " but the correct answer is " + correctBits + "!");

    // Start a new exercise now that this one is finished
    NewExercise();
}
